import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SearchSide from "@/components/SearchSide/SearchSide";
import { popularMovies, topRatedMovies } from "@/API/mainApi";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const popularMoviesData = await popularMovies(1);
  const topRatedMoviesData = await topRatedMovies(1);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div className="grid grid-cols-3 gap-6 p-10">
          <Skeleton height={100}  baseColor="#898996" count={20} highlightColor="#898996"/>
          <Skeleton height={100} baseColor="#898996"  count={20} highlightColor="#898996"/>
          <Skeleton height={100} baseColor="#898996" count={20} highlightColor="#898996"/>
        </div>}>
          <Sidebar />
          {children}
          <SearchSide
            popularMoviesData={popularMoviesData}
            topRatedMoviesData={topRatedMoviesData}
          />
        </Suspense>
      </body>
    </html>
  );
}
